uim_username = "administrator"
uim_password = "interOP@123"
uimserver = '10.17.188.162'
vm_username = 'root'
vm_password = 'interOP@123'
domain = r'/C8SERVER1_domain/C8SERVER1_hub/C8SERVER1'
uimpath = r'/opt/nimsoft'
probe_deactivate = r"""{}/bin/pu -u {} -p {} {}/controller probe_deactivate automated_deployment_engine""".format(uimpath, uim_username, uim_password, domain)
probe_activate = r"""{}/bin/pu -u {} -p {} {}/controller probe_activate automated_deployment_engine""".format(uimpath, uim_username, uim_password, domain)
probe_deploy = r"""{}/bin/pu -u {} -p {} {}/automated_deployment_engine deploy_probe probename""".format(uimpath, uim_username, uim_password, domain)
uimversion = 201
port = 22