import os
uimUsername = "administrator"
uimPassword = "interOP@123"
uimServer = "10.17.190.53"
uimServerLoginName = "administrator"
uimServerLoginPassword = "interOP@123sys"
fileShareIP = "10.17.172.178"
fileShareUserName = "administrator"
fileSharePassword = "interOP@123"
hostName = "W12R2SERVER1"
domain = r"/W12R2SERVER1_domain/W12R2SERVER1_hub/W12R2SERVER1"
uimPath = r"C:\PROGRA~1\Nimsoft"
uimapi_version = "9.10"
ump_robot_path = r"/W12R2SERVER1_domain/W12R2SERVER1_hub/w12r2ump1"
probe_status = r"""{}\bin\pu -u {} -p {} {}/controller probe_status automated_deployment_engine""".format(uimPath, uimUsername, uimPassword, domain)
probe_deactivate = r"""{}\bin\pu -u {} -p {} {}/controller probe_deactivate automated_deployment_engine""".format(uimPath, uimUsername, uimPassword, domain)
probe_activate = r"""{}\bin\pu -u {} -p {} {}/controller probe_activate automated_deployment_engine""".format(uimPath, uimUsername, uimPassword, domain)
probe_deploy = r"""{}\bin\pu -u {} -p {} {}/automated_deployment_engine deploy_probe probename""".format(uimPath, uimUsername, uimPassword, domain)
ump_uimapi_deploy = r"""{}\bin\pu -u {} -p {} {}/automated_deployment_engine deploy_probe uimapi {} {}""".format(uimPath, uimUsername, uimPassword, domain, uimapi_version, ump_robot_path)
uim_https_port = r"""{}\bin\pu -u {} -p {} {}/controller probe_config_set wasp setup https_port 8084""".format(uimPath, uimUsername, uimPassword, domain)
uim_contact_origins_enabled = r"""{}\bin\pu -u {} -p {} {}/controller probe_config_set wasp setup contact_origins_enabled true""".format(uimPath, uimUsername, uimPassword, domain)
ump_https_port = r"""{}\bin\pu -u {} -p {} {}/controller probe_config_set wasp setup https_port 8084""".format(uimPath, uimUsername, uimPassword, ump_robot_path)
ump_contact_origins_enabled = r"""{}\bin\pu -u {} -p {} {}/controller probe_config_set wasp setup contact_origins_enabled true""".format(uimPath, uimUsername, uimPassword, ump_robot_path)
uimVersion = "920"